apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.name }}
spec:
    replicas: {{ .Values.replicaCount }}   
    selector:
      matchLabels:
        app: {{ .Values.service.name }}
    template:
      metadata:
        labels:
          app: {{ .Values.service.name }}
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "3000"
      spec:
        containers:
        - name: {{ .Values.service.name }}
          image: "{{ .Values.image.repository }}{{ if .Values.image.digest }}@{{ .Values.image.digest }}{{ else }}:{{ .Values.image.tag | default "latest" }}{{ end }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.service.targetPort }}
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 512Mi
          env:
          - name: {{ .Values.secrets.mongo.envName }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.mongo.secretName }}
                key: {{ .Values.secrets.mongo.key }}
